name: publish-packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.101

      - name: Install dependencies
        run: dotnet restore Source/

      - name: Build
        run: dotnet build Source/ --configuration Release --no-restore
      
      - name: Publish
        run: dotnet publish Source/ -c release -o ~/publish

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ErosionFinderCLI
          path: ~/publish