name: publish-packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.101

      - name: Install dependencies
        run: dotnet restore Source/

      - name: Set version
        run: echo "VERSION=$(grep '<Version>' < Source/ErosionFinder.Ui.ConsoleApplication/ErosionFinder.Ui.ConsoleApplication.csproj | sed 's/.*<Version>\(.*\)<\/Version>/\1/')" >> $GITHUB_ENV

      - name: Build
        run: dotnet build Source/ --configuration Release --no-restore
      
      - name: Publish
        shell: bash
        run: |          
          release_name="erosion-finder-cli-v${{ secrets.VERSION }}"

          dotnet publish Source/ -c release -o "$release_name"

          tar czvf "${release_name}.tar.gz" "$release_name"

          rm -r "$release_name"

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: "erosion-finder-cli*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}